
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    depends_on:
      - mongo
    dns:
      - 8.8.8.8       # ← AJOUTE ÇA
      - 1.1.1.1       # ← (optionnel, DNS secondaire Cloudfl 

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - backend
    dns:
      - 8.8.8.8       # ← AJOUTE ÇA
      - 1.1.1.1       # ← (optionnel, DNS secondaire Cloudfl
